-- mvc board를 위한 sql
-- BOARD TABLE DROP CREATE
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
DROP TABLE BOARD;
CREATE TABLE BOARD(
        BID      NUMBER(6)      PRIMARY KEY,
        BNAME    VARCHAR2(50)   NOT NULL,
        BTITLE   VARCHAR2(100)  NOT NULL,
        BCONTENT VARCHAR2(2500),
        BDATE    DATE           DEFAULT SYSDATE,
        BHIT     NUMBER(6)      DEFAULT 0 NOT NULL,
        BGROUP   NUMBER(6)      NOT NULL,
        BSTEP    NUMBER(6)      NOT NULL,
        BINDENT  NUMBER(6)      NOT NULL,
        BIP      VARCHAR2(50)   NOT NULL
        );

-- DUMMY DATA
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP )
    VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '글1', '본문1', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP )
    VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '글2', '본문2', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
-- 1번 글의 답변 더미데이터
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP )
    VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '답)글1', '답글1', 1, 1, 1, '192.168.10.30');
       
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;  

-- DAO에 들어갈 QUERY

-- 글목록 (startRow endRow)
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP; -- 글 출력순서
SELECT *
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP)A )
    WHERE RN BETWEEN 2 AND 3;

-- 전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;

-- 글쓰기 
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP )
    VALUES (BOARD_SEQ.NEXTVAL, '홍길동', '글3', '본문3', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
    
-- BID로 조회수 올리기
UPDATE BOARD SET BHIT=BHIT+1 WHERE BID=1;

-- 글 상세보기 (BID로 DTO가져오기)
SELECT * FROM BOARD WHERE BID = 1;

-- 답변글 쓰기전 스텝
SELECT * FROM BOARD WHERE BGROUP = 1; -- 1번 GROUP출력
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP = 1 AND BSTEP > 0;


-- 답변글 쓰기
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP )
    VALUES (BOARD_SEQ.NEXTVAL, '홍답', '답글1-2', '답글1-2', 1, 1, 1, '192.168.10.30');

-- 글 수정
UPDATE BOARD SET BNAME = '홍길동 답',
                 BTITLE = '답)글1-2',
                 BCONTENT = '답글1-2',
                 BIP = '111.111.11.1'
                 WHERE BID =4;
-- 글 삭제

DELETE FROM BOARD WHERE BID = 2;

COMMIT;


