SHOW USER;
SELECT * FROM USER_TABLES; -- SCOTT2가 가지고 있는 유저 테이블
SELECT * FROM ALL_TABLES; -- SCOTT2RK 접근 가능한 테이블
SELECT * FROM ALL_TABLES WHERE TABLE_NAME IN ('DEPT', 'EMP');
SELECT * FROM SCOTT.EMP;
SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D WHERE E.DEPTNO=D.DEPTNO;
EXIT;