-- [XII] TRANSACTION 명령어
-- COMMIT; (트랜잭션 반영), ROLLBACK (트랜잭션 취소), SAVEPOINT (트랜잭션 분할)
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01; -- 10,20,30,40
DELETE FROM DEPT01;
SELECT * FROM DEPT01; --  삭제확인, 필드는 보유하나 필드값은 삭제
ROLLBACK; -- 새로운 트랜잭션 시작 
SELECT * FROM DEPT01; -- 롤 백후 필드값 복원 
DELETE FROM DEPT01 WHERE DEPTNO=40;
COMMIT; -- DATABASE에 영구히 등록
-- 새로운 트랜잭션 시작 
SELECT * FROM DEPT01; -- 40번 지워진채로 출력 10, 20, 30
DELETE FROM DEPT01 WHERE DEPTNO=30;
SELECT * FROM DEPT01; -- 10, 20
SAVEPOINT C1; -- 10, 20
DELETE FROM DEPT01 WHERE DEPTNO=20;
SAVEPOINT C2; -- 10
DELETE FROM DEPT01 WHERE DEPTNO=10;
SELECT * FROM DEPT01; -- 아무것도 없음.
ROLLBACK TO C2;
SELECT * FROM DEPT01; -- 10
ROLLBACK TO C1;
SELECT * FROM DEPT01; -- 20, 10












