-- CUSTOMER 테이블의 CNO번호는 시퀀스(CUS_SQ)를 생성한 뒤 자동생성 번호로 입력되도록 한다(5점).

-- 두 개의 테이블의 내용을 이용하여 아래와 같이 출력되도록 SQL문을 추가 작성한다(15점).

CREATE TABLE CUS_LEVEL(  -- 테이블 생성
            LEVELNO NUMBER(20) PRIMARY KEY,
            LEVELNAME VARCHAR2(50) NOT NULL
            );
INSERT INTO  CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO  CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO  CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO  CUS_LEVEL VALUES (4, 'BLACK');
SELECT * FROM CUS_LEVEL;
CREATE TABLE CUSTOMER( -- 테이블 생성
            CNO      NUMBER(5)     PRIMARY KEY,
            CNAME    VARCHAR2(50)  NOT NULL,
            JOINDATE DATE          DEFAULT SYSDATE,
            PHONE    VARCHAR2(50)  UNIQUE,
            POINT    NUMBER(20),
            LEVELNO  NUMBER(20) REFERENCES CUS_LEVEL (LEVELNO)
            );
CREATE SEQUENCE CUSTOMER_SEQ -- 시퀀스 생성
  MAXVALUE 9999      
  MINVALUE 1         
  NOCACHE            
  NOCYCLE   ;

DROP SEQUENCE CUSTOMER_SEQ;
DROP TABLE CUSTOMER;
INSERT INTO CUSTOMER 
    VALUES (CUSTOMER_SEQ.NEXTVAL , '홍길동', '22/03/10', '010-9999-9999', 0, 1);  
 INSERT INTO CUSTOMER 
    VALUES (CUSTOMER_SEQ.NEXTVAL , '이철수', '22/04/19', '010-8888-8888', NULL, 2); 
  
 SELECT * FROM CUSTOMER;
 
 SELECT CNO, CNAME, TO_CHAR(JOINDATE, 'YYYY-MM-DD') JOINDATE, PHONE, POINT, LEVELNAME
    FROM CUSTOMER C1, CUS_LEVEL C2
    WHERE C1.LEVELNO = C2.LEVELNO;
  
  
  
  
  
  
  