-- [III] JOIN : 테이블 2개 이상을 연결하여 검색
SELECT * FROM EMP WHERE ENAME='SCOTT'; -- 부서번호 DEPTNO 20
SELECT * FROM DEPT;

-- CROSS JOIN (FROM 에 테이블을 2개 이상 넣기)
SELECT * FROM EMP, DEPT WHERE ENAME = 'SCOTT';
SELECT * FROM EMP, DEPT; 14 4 56 행

--1. EQUI JOIN (동등조건) : 공통필드엔 DEPTNO 값이 일치되는 조건만 JOIN.
SELECT * FROM EMP, DEPT WHERE ENAME ='SCOTT' AND EMP.DEPTNO=DEPT.DEPTNO;
SELECT EMPNO,ENAME,JOB, MGR, HIREDATE, SAL, COMM, EMP.DEPTNO, DNAME, LOC FROM EMP, DEPT WHERE EMP.DEPTNO=DEPT.DEPTNO;
  -- 테이블의 별칭
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, E.DEPTNO, DNAME, LOC FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO;
  
  --EX. 급여가 2000이상인 사람만 이름, 직책, 급여, 부서명, 근무지 출력.
SELECT ENAME, JOB, SAL, DNAME, LOC  FROM EMP E , DEPT D WHERE E.DEPTNO=D.DEPTNO AND SAL>=2000;

  --EX. 근무지가 'CHICAGO'인 사람의 이름, 업무, 급여, 부서번호, 근무지를 출력 
SELECT ENAME, JOB, SAL, E.DEPTNO, LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC = 'CHICAGO';

  --EX. 부서번호가 10이거나 20번인 사원의 이름, 업무, 근무지, 급여. 급여순 정렬
SELECT ENAME, JOB, LOC, SAL FROM EMP E, DEPT D WHERE E.DEPTNO=D.DEPTNO AND E.DEPTNO IN (10, 20) ORDER BY SAL; 

  --EX. JOB이 SALESMAN이거나 MANAGER인 사원의 이름, 급여, 상여, 연봉 ((SAL+COMM)*12), 부서명, 근무지를 출력 (연봉이 큰 순으로 출력)
SELECT ENAME, SAL, COMM, ((SAL+NVL(COMM,0))*12) "연봉", DNAME, LOC FROM EMP, DEPT WHERE JOB = 'SALESMAN' OR JOB = 'MANAGER' ORDER BY 연봉 DESC; 
  
  --EX. COMM이 NULL이고 급여가 1200 이상인 사원의 이름, 급여, 입사일, 부서번호, 부서명 출력 부서명 급여가 큰 순서
SELECT ENAME, SAL, HIREDATE, EMP.DEPTNO, DNAME FROM EMP, DEPT WHERE EMP.DEPTNO = DEPT.DEPTNO AND SAL >= 1200 AND COMM IS NULL ORDER BY SAL DESC; 
  
  --EX. 'NEW YORK'에서 근무하는 사원의 이름과 급여 출력
SELECT ENAME, SAL FROM EMP, DEPT WHERE LOC = 'NEW YORK';  
  
  --EX. 'ACCOUNTING' 부서 소속의 사원 이름과 입사일 출력
SELECT ENAME, HIREDATE FROM EMP, DEPT WHERE DNAME = 'ACCOUNTING';  

  -- 직급이 MANAGER인 사원의 이름, 부서명을 출력하시오
SELECT ENAME, DNAME FROM EMP, DEPT WHERE JOB = 'MANAGER';  

  -- Comm이 null이 아닌 사원의 이름, 급여, 부서코드, 근무지를 출력하시오.
SELECT ENAME, SAL, D.DEPTNO, LOC FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND COMM IS NOT NULL;  

-- 2. NON EQUI JOIN
SELECT * FROM EMP WHERE ENAME = 'SCOTT'; -- 사원 정보
SELECT * FROM SALGRADE; -- 급여 등급 정보
-- CROSS JOIN = EMP의 1행 * SALGRADE의 5행
SELECT * FROM EMP, SALGRADE WHERE ENAME = 'SCOTT';










