DROP TABLE MAJOR;

COMMIT;

CREATE TABLE MAJOR(
        MNO NUMBER(20) PRIMARY KEY,
        MNAME VARCHAR2(200) NOT NULL
        );
INSERT INTO MAJOR VALUES (1, '빅데이터학');
INSERT INTO MAJOR VALUES (2, '경영정보학'); 
INSERT INTO MAJOR VALUES (3, '컴퓨터공학'); 
INSERT INTO MAJOR VALUES (4, '문헌정보학'); 
INSERT INTO MAJOR VALUES (5, '인공지능학'); 

SELECT * FROM MAJOR;

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
       SNO NUMBER(20) PRIMARY KEY,
       SNAME VARCHAR2(200) NOT NULL,
       MNO NUMBER(20) REFERENCES MAJOR(MNO),   
       SCORE NUMBER(20) DEFAULT 0 CHECK (SCORE BETWEEN 0 AND 100),
       EXPEL NUMBER(20) DEFAULT 0 CHECK (EXPEL BETWEEN 0 AND 1)
        );
DROP SEQUENCE STU_SEQ;        
CREATE SEQUENCE STU_SEQ
        MAXVALUE 999
        MINVALUE 1
        NOCACHE
        NOCYCLE;

INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '서지수', 1, 96, 0);
INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '류수정', 1, 99, 0);
INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '유지애', 3, 87, 0);
INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '이수정', 5, 97, 0);
INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '김지연', 2, 95, 0);
INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '박제적', 1, 70, 1);    
INSERT INTO STUDENT VALUES
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '이미주', 3, 75, 0);    
    
    
SELECT * FROM STUDENT;

COMMIT;

-- 학번 검색

SELECT SNAME, MNO, SCORE FROM STUDENT WHERE SNO = 2022004;

-- 이름 검색 

SELECT SNO, SNAME, MNAME, SCORE
    FROM MAJOR M, STUDENT S WHERE M.MNO = S.MNO AND SNAME = '서지수';
    
-- 전공 검색    

SELECT ROWNUM||'등', A.*
FROM (SELECT SNAME || SNO, MNAME || S.MNO, SCORE 
FROM MAJOR M, STUDENT S WHERE M.MNO = S.MNO AND MNAME = '컴퓨터공학' AND S.EXPEL = 0
ORDER BY SCORE DESC) A;

-- 학생 입력

INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) VALUES 
    (TO_NUMBER(EXTRACT (YEAR FROM SYSDATE), '9999')||TRIM('00'||STU_SEQ.nextval), '박명은', 
    (SELECT MNO FROM MAJOR WHERE MNAME='인공지능학'), 77);
    
-- 학생 수정
UPDATE STUDENT SET SCORE = 67,
                   SNAME = '최제적',
                   MNO = (SELECT MNO FROM MAJOR WHERE MNAME = '인공지능학') 
            WHERE SNO = 20220012;
            
-- 학생출력
SELECT ROWNUM, A.*
FROM (SELECT SNAME, SNO, MNAME, S.MNO MNO, SCORE 
FROM MAJOR M, STUDENT S WHERE M.MNO = S.MNO AND S.EXPEL = 0
ORDER BY SCORE DESC) A;

-- 동일인물 있을시 출력
SELECT SNO, SNAME, MNAME, SCORE FROM MAJOR M, STUDENT S WHERE M.MNO = S.MNO AND SNAME = '서지수' ORDER BY SCORE DESC;

-- 제적 처리
UPDATE STUDENT SET EXPEL = 1 WHERE SNO = 20220012 AND SNAME = '최제적';

-- 제적자 출력
SELECT ROWNUM||'등', A.*
FROM (SELECT SNAME || SNO, MNAME || S.MNO, SCORE 
FROM MAJOR M, STUDENT S WHERE M.MNO = S.MNO AND S.EXPEL = 1
ORDER BY SCORE DESC) A;





