CREATE TABLE CUS_LEVEL(
        LEVELNO NUMBER(10) PRIMARY KEY,
        LevelName VARCHAR2(30),
        LOW NUMBER(10),
        HIGH NUMBER(10)
        );
INSERT INTO cus_level VALUES (1, 'BRONZE', 0, 50000);
INSERT INTO cus_level VALUES (2, 'SILVER', 50001, 100000);
INSERT INTO cus_level VALUES (3, 'GOLD', 100001, 500000);
INSERT INTO cus_level VALUES (4, 'VIP', 500001, 1000000);

 SELECT * FROM CUS_LEVEL;
 DROP TABLE CUS_LEVEL;
 SELECT C.LEVELNO FROM CUS_LEVEL L, CUSTOMER C WHERE l.levelno = c.levelno AND CAMOUNT BETWEEN L.LOW AND L.HIGH;
CREATE TABLE CUSTOMER(
        CID     NUMBER(10)      PRIMARY KEY,
        CTEL    VARCHAR2(30)    NOT NULL,
        CNAME   VARCHAR2(30)    NOT NULL,
        CPOINT  NUMBER(10)      DEFAULT 1000,
        CAMOUNT NUMBER(10)      DEFAULT 0,
        LEVELNO NUMBER(10)      DEFAULT 1 REFERENCES CUS_LEVEL(LEVELNO) 
        );
INSERT INTO CUSTOMER VALUES 
    (CUSTOMER_SEQ.NEXTVAL, '010-1111-1111', '홍길동', 2000, 7000, 1);  
INSERT INTO CUSTOMER VALUES 
    (CUSTOMER_SEQ.NEXTVAL, '010-2222-2222', '대길동', 3000, 9000, 1);
INSERT INTO CUSTOMER VALUES 
    (CUSTOMER_SEQ.NEXTVAL, '010-1111-3333', '태길동', 6000, 18000, 2);
    
SELECT * FROM CUSTOMER;
DROP TABLE CUSTOMER;

DROP SEQUENCE CUSTOMER_SEQ;
CREATE SEQUENCE CUSTOMER_SEQ
        MAXVALUE 9999
        MINVALUE 1
        NOCACHE
        NOCYCLE;

COMMIT;

-- 1. 아이디 검색 (”다음 level이 업그레이드되기 위해 쓸 돈”)

SELECT CID, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO!=5) FORLEVEL
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO AND CID = 1;

-- 2. 폰4자리(FULL)검색 
    
-- 3. 고객이름 검색
SELECT CID, CNAME, CPOINT, CAMOUNT, LEVELNAME,
    (SELECT HIGH-CAMOUNT+1 FROM CUSTOMER WHERE CID = C.CID AND LEVELNO!=5) FORLEVEL
    FROM CUSTOMER C, CUS_LEVEL L
    WHERE C.LEVELNO = L.LEVELNO AND CNAME = '대길동';

--4. 포인트로만 구매
UPDATE CUSTOMER SET CPOINT = CPOINT-500 WHERE CID = 1;

--5. 물품구매
UPDATE CUSTOMER SET CAMOUNT = CAMOUNT +500 WHERE CID = 1;

